### PR TITLE
Adds new scanner api for tailing logs

### PR DESCRIPTION
**Pull request by apoydence**
I'm doing a pull request to see if anyone thinks this API looks better.  The API avoids exposing channels, but is still thread safe.  

It only does the TailingLogs, but would be very easy to implement the others if required.

### CODE REVIEW

**Comment by jmtuley** [comment]
Any particular reason to prefer this over channels? I think I'm missing something, because I don't really feel strongly towards one pattern or the other. (Except insofar as to note that the CLI already is using channel-based code, so this would require a rewrite there – but I don't know how big a deal that is.)

**Comment by apoydence** [comment]
What I'm looking for is a discussion about which interface feels cleaner.  I figured the best way to decide would be to see and use both ways.

**Comment by jmtuley** [comment]
I think it's a fair question, and I think that it'll be a good discussion. I was just asking if there were any specific reasons.

Looking forward to talking about it in more detail!

**Comment by dsabeti** [comment]
This is pretty old.  We really like the fact that it doesn't expose channels, and Rohit says we'll considered for NOAA v2. We are closing this for now.

**Pull request closed without merging**
